title: Militant History
email: ""
description: >-
  Reproducing the history of the Committee for a Workers’ International.
baseurl: ""
url: ""
exclude:
  - LICENSE-agpl-3.0.md
  - LICENSE-cc-by-sa-4.0.md
  - LICENSE-fdl-1.3.md
sass:
  style: compressed

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
  books:
    output: true
    permalink: /books/:slug/
  chapters:
    output: true
    permalink: /books/:path/
  lm_issues:
    output: true
    permalink: /lm/:slug/
  lm_articles:
    output: true
    permalink: /lm/:path/
  encyclopedia:
    output: true
    permalink: /enc/:slug/