title: Militant History
url: "https://www.militanthistory.org"
exclude:
  - LICENSE-gpl-3.0.md
  - LICENSE-cc-by-sa-4.0.md
sass:
  style: compressed
kramdown:
  parse_block_html: true

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
  lm_issues:
    output: true
    permalink: /lm/:slug/
  lm_articles:
    output: true
    permalink: /lm/:path/
  encyclopedia:
    output: true
    permalink: /enc/:path/