backend:
  name: github
  repo: jackwillis/militanthistory
publish_mode: editorial_workflow
media_folder: 'uploads/'
collections:
  - name: 'lm_articles'
    label: 'Labor Militant Articles'
    folder: '_lm_articles/'
    path: '{{lm_issue}}/{{slug}}'
    fields:
      - { name: title }
      - { name: lm_issue }
      - { name: author }
  - name: 'lm_issues'
    label: 'Labor Militant Issues'
    folder: '_lm_issues/'
    fields:
      - { name: subtitle }
      - { name: lm_issue }